### PR TITLE
upgrading eve to release 0.6 instead of commit and modifying the commit of superdesk-core

### PR DESCRIPTION
**Pull request by sivakuna-aap**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
@amagdas any specific reason for closing this? any specific reason for not having consistent versions across core and this repo?

**Comment by amagdas** [comment]
A rebase was needed so I close this PR and pushed the changes directly: https://github.com/superdesk/superdesk-content-api/commit/c94e81467bf9b9a616e77bfcf7676ecc3fe6a120

**Comment by sivakuna-aap** [comment]
great. Didn't notice it. But superdesk-core is still pointing to old SHA.

**Comment by amagdas** [comment]
Yup, will fix.

**Pull request closed without merging**
