### PR TITLE
Prepare eve

### PR DESCRIPTION
**Pull request by amagdas**
Prepare for Eve 0.6 release.
Fix publish and fetching.

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1:

**Comment by amagdas** [comment]
Ping @superdesk/developers

**Comment by amagdas** [comment]
Ping again @superdesk/developers

**Comment by mugurrus** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
Can this PR combined with https://github.com/superdesk/superdesk-content-api/pull/8?

**Pull request merged**
